### PR TITLE
fix: comparison between signed and unsigned integer expressions

### PR DESCRIPTION
**Pull request by bzEq**
which leads to [-Werror=sign-compare]

### CODE REVIEW

**Comment by miloyip** [comment]
This seems incorrect.
You should not narrow `u` to do the comparison.

**Comment by bzEq** [comment]
Yes, you are right. I just noticed the "else" branch deals with wider range. It seems I should cast the `std::numeric_limits<lua_Integer>::max()`  instead of  `u`

**Comment by bzEq** [comment]
@miloyip Yes, you are right. I just noticed that the `else` branch will deal with wider range. I should cast `std::numeric_limits<lua_Integer>::max()`, which is a positive number, instead of `u`.

**Comment by bzEq** [comment]
It seems the compiler will promote `std::numeric_limits<lua_Integer>::max()` automatically. The cast of `std::numeric_limits<lua_Integer>::max()` just makes compiler happier...

**Comment by xpol** [comment]
commit 2d1216128eda3616395747f2934326afe33e9fd4 should make compiler happier.

**Pull request closed without merging**
